<a href="https://colab.research.google.com/github/tallman1O/TensorFlow-Deep-Learning/blob/main/01_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamental Concepts of Tensors using Tensorflow

In [3]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [5]:
# Create tensors with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scaler.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimension of our vector
vector.ndim

1

In [9]:
# Create matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [15]:
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]  # Removed the inner nesting
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [16]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scaler, a 1-d tensor is a vector)